# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:34
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20160928_0540'),
    ]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projectmodulesconfig",
                column_name="config",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="roles",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="default_options",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="epic_statuses",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="us_statuses",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="points",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="task_statuses",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="issue_statuses",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="issue_types",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="priorities",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="projects_projecttemplate",
                column_name="severities",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
