# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20160928_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_contact_activated',
            field=models.BooleanField(default=True, verbose_name='active contact'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='is_contact_activated',
            field=models.BooleanField(default=True, verbose_name='active contact'),
        ),
    ]
