# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_attributes', '0010_auto_20160928_0540'),
    ]

    operations = [
        # Function: Remove a key in a json field
        migrations.RunSQL(
            """
        CREATE OR REPLACE FUNCTION "json_object_delete_keys"("json" jsonb, VARIADIC "keys_to_delete" text[])
                           RETURNS jsonb
                          LANGUAGE sql
                         IMMUTABLE
                            STRICT
                                AS $function$
                   SELECT COALESCE ((SELECT ('{' || string_agg(to_json("key") || ':' || "value", ',') || '}')
                                       FROM jsonb_each("json")
                                      WHERE "key" <> ALL ("keys_to_delete")),
                                    '{}')::jsonb $function$;
            """,
            reverse_sql="""
        DROP FUNCTION IF EXISTS "json_object_delete_keys"("json" jsonb, VARIADIC "keys_to_delete" text[])
                        CASCADE;"""
        ),
    ]
