# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:34
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0013_historyentry_values_diff_cache'),
    ]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="delete_comment_user",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="comment_versions",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="values_diff_cache",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="user",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="diff",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="snapshot",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
                ALTER TABLE {table_name}
                   ALTER COLUMN {column_name}
                           TYPE jsonb
                          USING {column_name}::text::jsonb;
            """.format(
                table_name="history_historyentry",
                column_name="values",
            ),
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
